### ISSUE TITLE
Colors not replacing in VentureChat ChatChannelHookMessageFormat

### ISSUE THREAD

**Issue by Androkai** [Scarsz/DiscordSRV#36]
Normal ChatChannelHookMessageFormat is:
`ChatChannelHookMessageFormat: "%channelcolor%[%channelnickname%]&r %message%"`

With VentureChat (only tested with it till now) I have to replace `&` with `§` to make it work:
`ChatChannelHookMessageFormat: "%channelcolor%[%channelnickname%]§r %message%"`

I also use colorcodes I had to replace for my own format:
`ChatChannelHookMessageFormat: "§8[%channelcolor%%channelnickname%§8]§r %message%"`

Maybe this also have to be done for other chatchannel-plugins (needs testing).

The second problem is that Venturechat define color as text within config which is normally replaced later but in combination with DiscordSRV this doesn't work and results in something like that:

DiscordSRV-config:
```
ChatChannelHookMessageFormat: "§8[%channelcolor%%channelnickname%§8]§r %message%"
```
VentureChat-config:
```
channels:
  Admin:
    color: red
    chatcolor: red
    mutable: false
    filter: false
    autojoin: true
    default: false
    distance: 0
    cooldown: 0
    bungeecord: false
    alias: a
    permissions: adminchannel
    format: '&f[&cAdmin&f] {prefix} {nickname}&c:'
    irc: false
```
Output:
![Output](https://androkai.net/bilder/DiscordSRV_VentureChatFormatBug.png)

"red" as the channelcolor in front of channelnickname (which is short "a" for AdminChannel) is no longer replaced correctly. I also experimented with using &c or §c in the VentureChat-config but this doesn't work at all.
